#!/bin/bash
#description :Tomcat 8 Start Stop Restart
#processname:tomcat8
#chkconfig:234 20 80
JAVA_HOME=/usr/java/jdk1.8.0_151
PATH=$JAVA_HOME/bin:$PATH
export PATH

CATALINA_HOME=/usr/tomcat/apache-tomcat-8.5.24
case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
status)
    #
    # Restart Tomcat
    #
    ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap" | awk '{printf $1 " "}' | wc | awk '{print $2}' > /tmp/tomcat_process_count.txt
    read line < /tmp/tomcat_process_count.txt
    if [ $line -gt 0 ]; then
       echo -n "tomcat8 ( pid "
       ps ax --width=1000 | grep "[o]rg.apache.catalina.startup.Bootstrap" | awk '{printf $1 " "}'
       echo ") is running                             "
    else
       echo "tomcat8 is stopped"
    fi
    ;;

  *)
    echo "Usage tomcat8 start/stop/restart/status"
    exit 1;;

esac

exit 0

